#ifndef _CONSOLE
	#define ID_KICK 101
	#define ID_BAN 102
	#define ID_ABOUT 104
	#define ID_LOG 105
	#define ID_ICON 106

	#define ID_TRAY_HIDE 118
	#define ID_TRAY_SHUTDOWN 119
	#define ID_STATUS_BAR 120

	#define ID_MENU 200

	#define ID_MENU_FILE_CLEARLOG 201
	#define ID_MENU_FILE_SHUTDOWN 202

	#define ID_MENU_GAME_REJECT 203
	#define ID_MENU_GAME_ACCEPT 204
	#define ID_MENU_GAME_BROADCAST 205

	#define ID_MENU_GAME_PLAYERS_LIST 206
	#define ID_MENU_GAME_PLAYERS_SAVE 207

	#define ID_MENU_GAME_RELOAD_ACTIONS 208
	#define ID_MENU_GAME_RELOAD_CREATUREEVENTS 209
	#define ID_MENU_GAME_RELOAD_COMMANDS 210
	#define ID_MENU_GAME_RELOAD_CONFIG 211
	#define ID_MENU_GAME_RELOAD_GLOBALEVENTS 212
	#define ID_MENU_GAME_RELOAD_HIGHSCORES 213
	#define ID_MENU_GAME_RELOAD_MONSTERS 214
	#define ID_MENU_GAME_RELOAD_MOUNTS 215
	#define ID_MENU_GAME_RELOAD_MOVEMENTS 216
	#define ID_MENU_GAME_RELOAD_NPCS 217
	#define ID_MENU_GAME_RELOAD_QUESTS 218
	#define ID_MENU_GAME_RELOAD_RAIDS 219
	#define ID_MENU_GAME_RELOAD_SPELLS 220
	#define ID_MENU_GAME_RELOAD_TALKACTIONS 221
	#define ID_MENU_GAME_RELOAD_RELOADALL 222

	#define ID_MENU_GAME_WORLDTYPE_NOPVP 223
	#define ID_MENU_GAME_WORLDTYPE_PVP 224
	#define ID_MENU_GAME_WORLDTYPE_PVPENFORCED 225
#endif

#define STATUS_SERVER_NAME "The Forgotten Server"
#define STATUS_SERVER_CODENAME "Mystic Spirit"
#define STATUS_SERVER_PROTOCOL "9.61"
#define STATUS_SERVER_VERSION "0.2.14"
#define STATUS_SERVER_DEVELOPERS "Talaturen, Kornholijo, Elf and Tryller"
