#ifndef __CONSOLE__
	#define ID_KICK 101
	#define ID_BAN 102
	#define ID_ABOUT 104
	#define ID_LOG 105
	#define ID_ICON 106

	#define ID_TRAY_HIDE 118
	#define ID_TRAY_SHUTDOWN 119
	#define ID_STATUS_BAR 120

	#define ID_MENU 200

	#define ID_MENU_MAIN_REJECT 201
	#define ID_MENU_MAIN_ACCEPT 202
	#define ID_MENU_MAIN_CLEARLOG 203
	#define ID_MENU_MAIN_SHUTDOWN 204

	#define ID_MENU_SERVER_WORLDTYPE_NOPVP 205
	#define ID_MENU_SERVER_WORLDTYPE_PVP 206
	#define ID_MENU_SERVER_WORLDTYPE_PVPENFORCED 207

	#define ID_MENU_SERVER_BROADCAST 208
	#define ID_MENU_SERVER_SAVE 209
	#define ID_MENU_SERVER_CLEAN 210
	#define ID_MENU_SERVER_CLOSE 211
	#define ID_MENU_SERVER_OPEN 212

	#define ID_MENU_SERVER_PLAYERBOX 213

	#define ID_MENU_RELOAD_ACTIONS 214
	#define ID_MENU_RELOAD_COMMANDS 215
	#define ID_MENU_RELOAD_CONFIG 216
	#define ID_MENU_RELOAD_CREATUREEVENTS 217
	#define ID_MENU_RELOAD_GLOBALEVENTS 218
	#define ID_MENU_RELOAD_HIGHSCORES 219
	#define ID_MENU_RELOAD_MONSTERS 220
	#define ID_MENU_RELOAD_MOVEMENTS 221
	#define ID_MENU_RELOAD_NPCS 222
	#define ID_MENU_RELOAD_QUESTS 223
	#define ID_MENU_RELOAD_RAIDS 224
	#define ID_MENU_RELOAD_SPELLS 225
	#define ID_MENU_RELOAD_TALKACTIONS 226
	#define ID_MENU_RELOAD_HOUSEPRICES 227
	#define ID_MENU_RELOAD_ALL 228
#endif

#define STATUS_SERVER_NAME "The Forgotten Server"
#define STATUS_SERVER_VERSION "0.3"
#define STATUS_SERVER_CODENAME "Pre-Alpha"
#define STATUS_SERVER_PROTOCOL "8.2"
#define CLIENT_VERSION_MIN 820
#define CLIENT_VERSION_MAX 822
#define CLIENT_VERSION_STRING "Only clients with protocol 8.2 allowed!"
