/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef THEFORGOTTENSERVER-DEBUG_PRIVATE_H
#define THEFORGOTTENSERVER-DEBUG_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.2.7.0"
#define VER_MAJOR	0
#define VER_MINOR	2
#define VER_RELEASE	7
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"0.2.7-debug"
#define FILE_DESCRIPTION	"The Forgotten Server"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"TheForgottenServer.exe"
#define PRODUCT_NAME	"The Forgotten Server"
#define PRODUCT_VERSION	"0.2.7-debug"

#endif /*THEFORGOTTENSERVER-DEBUG_PRIVATE_H*/
